### PR TITLE
feat: port the PR#8 onto latest main

### LINKED ISSUE #7: An "error reading file" error was caught when importing based on the current directory
With the following structure, when I try to import reboot.css with `@import './reboot.css';` in app.css, an "error reading file" error was caught. For work, I have to import it with `@import './src/reboot.css';`, but it's confusing.

```
app
├── package.json
├── postcss.config.js
├── src
│   ├── app.css
│   ├── reboot.css
├── dist
```

- reproduce link: Open https://stackblitz.com/edit/node-mu6fph?file=src%2Fapp.css and run `npm run dev`

### PR DESCRIPTION
**Pull request by revelt**
Ports the [PR#8](https://github.com/eriklharper/postcss-nested-import/pull/8) to the latest `main` (as of 1.1.0), fixes #7

### CODE REVIEW

**Comment by himerus** [comment]
Any chance of moving on this? 
It's a current blocker to our usage of the module.

**Comment by revelt** [comment]
@himerus yes, sorry for delay, I'll aim to carve a release during this bank holiday weekend

**Comment by revelt** [comment]
@himerus `1.2.0` has been released; please try it!

**Comment by himerus** [comment]
@revelt Thank you so much for this!!

I am setting it up now on a project, and will report back any issues as we evaluate this as an option for several challenges we face with our CSS needs for various applications.

**Pull request merged**
