### PR TITLE
fix: import files based on the current directory

### LINKED ISSUE #7: An "error reading file" error was caught when importing based on the current directory
With the following structure, when I try to import reboot.css with `@import './reboot.css';` in app.css, an "error reading file" error was caught. For work, I have to import it with `@import './src/reboot.css';`, but it's confusing.

```
app
├── package.json
├── postcss.config.js
├── src
│   ├── app.css
│   ├── reboot.css
├── dist
```

- reproduce link: Open https://stackblitz.com/edit/node-mu6fph?file=src%2Fapp.css and run `npm run dev`

### PR DESCRIPTION
**Pull request by linhe0x0**
resolve #7

### CODE REVIEW

**Comment by madhaze** [comment]
I tried the change you to import a file in the same directory
```
@nested-import './test.css';
```
I also tried to use `../` to go to parent directory.  I didn't get either to work.

**Comment by madhaze** [comment]
I tested and was able to import with relative paths to other css files.  This worked for me.

**Comment by revelt** [comment]
@madhaze thank you

**Comment by revelt** [comment]
Guys, sorry for taking ages to sort this. I've just released 1.1.0 and there were conflicts to this branch, so I patched that and raised a new PR — https://github.com/eriklharper/postcss-nested-import/pull/15

@linhe0x0 don't worry I'll attribute you properly
@chrissnyder2337 @madhaze guys please help to test the PR#15 branch

**Comment by revelt** [comment]
will be released through https://github.com/eriklharper/postcss-nested-import/pull/15 asap — I attributed you @linhe0x0 in the changelog — thanks again for the contribution, I'll close this PR; if you see anything that can be improved, raise a new PR

**Pull request closed without merging**
