### PR TITLE
feat: update dependencies, add more tests, improve the setup

### PR DESCRIPTION
**Pull request by revelt**
Features:

- `c8` for coverage and `uvu` for unit tests
- enforces 100% coverage
- removed Jest
- removed `console.log` which reports contents of the resolved `@import`
- moved mock test files into subfolder within `test/mocks/` (previously mock `vendors.css` was shipping to npm)
- updated to the latest v8 PostCSS (set as peer dependency)
- improved the algorithm to account for both single and double and missing quotes within `@import`
- improved the algorithm to try-catch `fs` errors and report them properly
- removed Travis, added GH actions
- `yarn` is assumed to be the preferred over `npm`, but added npm `lockfile` to gitignore and `.npmrc` just in case somebody forks and tries to run it using `npm i`
- added `prettier` and `eslint` to trigger VSCode to format/lint the code (previous setup wasn't picked up by VSCode plugins)
- committed a fresh yarn lock file (GH actions will expect it too)

Closes issues: #2, #3, #4, #5 (all of them, at least at the moment of writing this).

Reference of a similar setup: https://github.com/postcss/postcss-mixins by Andrey Sitnik.

I also tested on my setup by rewriting source code within `node_modules` with this PR's code, imports were resolving fine.

Please review.

### CODE REVIEW

**Review by eriklharper — APPROVED** [review]
Thanks for the contribution!  If the tests are looking good on your end, feel free to merge :)

**Comment by revelt** [comment]
@eriklharper I don't have rights to merge, I'm not a maintainer :) please do it

**Comment by revelt** [comment]
also, you'll have to publish to npm as well — the GH action will just validate the tests are passing but we're not automating the publishing — personally, my packages are on Semaphore because it's faster so I'm not the most knowledgeable person on GH actions, but I'm imagine we could eventually set up automating publishing of `main` branch — you'd just merge into `main` and it would trigger publishing

**Comment by eriklharper** [comment]
I have not used this plugin in many years, so if you want to try tackling that, feel free.

**Comment by revelt** [comment]
I'm happy to take the responsibility of becoming co-maintainer if you give me the permissions. If you wish to publish, merge, then git-pull on the local, then use `np` from Sindre Sorhus — his CLI guides through the whole publishing to npm process, does all the checks and so on.

**Comment by eriklharper** [comment]
There ya go!  I added you as a maintainer.

**Comment by revelt** [comment]
Awesome! You're still the sole publisher to npm https://docs.npmjs.com/cli/v8/commands/npm-owner so you'll have to publish to npm.

**Comment by alex-ketch** [comment]
Hi @eriklharper, would you be interested in adding something like this [NPM Publish](https://github.com/marketplace/actions/npm-publish) GitHub action?
It would help to automate publishing the package to NPM, without you having to relinquish control/auth of the package name or NPM credentials.

Unfortunately as it stands the package on NPM is outdated.

Thanks, and let me know if I can help at all!

**Pull request merged**
